### PR TITLE
Switch to poetry

### PR DESCRIPTION
**Pull request by abrahammurciano**
Checklist
* [ ] Added a ``news`` entry

### CODE REVIEW

**Comment by abrahammurciano** [comment]
Pipeline will pass after #7 is merged

**Comment by yamaton** [comment]
Bumping to v1.0.0 with this?

**Comment by abrahammurciano** [comment]
> Bumping to v1.0.0 with this?

I guess when we're done with everything we've planned we'll bump a major, so I just did it here in passing

**Comment by yamaton** [comment]
If it was deliberate, I'm fine with that.

**Pull request merged**
